site_name: Hakan Çelik
site_description: Hakan Çelik - Software Engineer at DeepInfo.
site_url: https://www.hakancelik.dev

repo_url: https://github.com/hakancelikdev/hakancelik.dev
repo_name: hakancelikdev/hakancelikdev.github.io
edit_uri: https://github.com/hakancelikdev/hakancelikdev.github.io/tree/main/docs

copyright: Copyright &copy; 2023 - 2025 Hakan Çelik

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - nl2br
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: true
      baselevel: 3
      title: İçindekiler
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      guess_lang: true
      auto_title: true
      auto_title_map:
        python: Python
        javascript: JavaScript
        html: HTML
        css: CSS
        bash: Bash
        shell: Shell
        yaml: YAML
        json: JSON
        sql: SQL
        django: Django
        jinja: Jinja2
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: tr
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
      enable_git_follow: true
      fallback_to_build_date: true
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-2EGM5WWEED
  consent:
    title: Çerez Onayı
    description: >-
      Tekrarlanan ziyaretlerinizi ve tercihlerinizi tanımak, dokümantasyonumuzun etkinliğini
      ölçmek ve kullanıcıların aradıklarını bulup bulmadığını anlamak için çerezler kullanıyoruz.
      Onayınızla dokümantasyonumuzu daha iyi hale getirmemize yardımcı oluyorsunuz.
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hakancelikdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hakancelikdev
    - icon: fontawesome/solid/globe
      link: https://hakancelik.dev
    - icon: fontawesome/brands/github
      link: https://github.com/hakancelikdev
    - icon: fontawesome/brands/telegram
      link: https://t.me/django_turkey
  homepage: https://hakancelik.dev
  generator: false

theme:
  name: material
  custom_dir: docs/overrides
  language: tr
  logo: "assets/images/profile.png"
  favicon: "assets/images/profile.png"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - search.share
    - search.boost
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.code.select.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    - content.action.print
    - content.footer.previous
    - content.footer.next
    - content.footer.nav
    - content.footer.track
    - toc.follow
    - toc.integrate
    - top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    previous: material/arrow-left
    next: material/arrow-right
    top: material/arrow-up
    search: material/magnify
    menu: material/menu
    language: material/translate
    theme: material/theme-light-dark
    expand: material/chevron-down
    collapse: material/chevron-up
    directory: material/folder
    file: material/file
    close: material/close
    check: material/check
    warning: material/alert
    info: material/information
    note: material/note-text
    tip: material/lightbulb
    example: material/format-list-checks
    bug: material/bug
    zap: material/lightning-bolt
    heart: material/heart
    star: material/star
    download: material/download
    share: material/share-variant
    print: material/printer
    external: material/open-in-new
    new_window: material/open-in-new
    fullscreen: material/fullscreen
    minimize: material/fullscreen-exit
  favicon: assets/images/profile.png

nav:
  - Overview: index.md
  - Subdomains: subdomains.md
  - Metaclasses in Python:
      - metaclasses/index.md
      - metaclasses/tutorial/understanding-python-classes.md
      - metaclasses/tutorial/dynamic-class-creation.md
      - metaclasses/tutorial/more-accurate-dynamic-class-creation.md
      - metaclasses/tutorial/metaclasses-in-python.md
      - metaclasses/tutorial/run-methods-order-in-python.md
      - metaclasses/tutorial/run-methods-order-in-python-with-more-explanation.md
      - metaclasses/tutorial/invisible-metaclasses-in-python.md
      - metaclasses/tutorial/meta-classes-without-type.md
      - metaclasses/tutorial/more-accurate-meta-classes-without-type.md
      - metaclasses/tutorial/examples/register-classes-in-python.md
      - metaclasses/tutorial/examples/singleton-in-python.md
      - metaclasses/tutorial/examples/auto-slots.md
      - metaclasses/tutorial/examples/logging-namespace.md
      - metaclasses/tutorial/examples/modeling-a-class-with-a-metaclass.md
      - metaclasses/tutorial/examples/define-method-if-condition-true.md
  - Git:
      - git/README.md
      - git/git-nedir-kurulumu-ve-ozgur-yazlm.md
      - git/git-komutlar.md
  - Python:
      - python/README.md
      - python/python-nedir.md
      - python/pythona-giris-anaconda-atom-ve-pip-kurulumu.md
      - python/fonksiyonlara-giris-type-fonksiyonu-degiskenler-ve-turleri-yorum-satr.md
      - python/islecler-ve-print-fonksiyonu.md
      - python/input-fonksiyonu-ozellikleri-ve-detayl-inceleme.md
      - python/tipler-ve-donusumleri-class-type.md
      - python/if-elif-ve-else-kosul-durumlar.md
      - python/pythonda-donguler.md
      - python/str-nesnesinin-methodlar-ve-method-operasyonlar-method-method-wrapper.md
      - python/pythonda-hata-yonetimi.md
      - python/kutuphane-modul-ve-paketler.md
      - python/instagram-botu.md
  - Django:
      - django/README.md
      - django/django-nedir.md
      - django/django-admin-actions.md
      - django/dumpdata-ve-loaddata-kullanm.md
      - django/ozel-yonetim-komutlar-nasl-yaplr.md
      - django/context-processors-fonksiyonlar-ve-kodlanmas.md
      - django/djangoda-sayfalama-pagination.md
      - django/django-ile-site-haritas-olusturma.md
      - django/user-modelini-genisletmek.md
      - django/birden-fazla-veri-taban-kullanm-multi-db.md
      - django/django-projesinde-birden-fazla-veri-taban-kullanm.md
      - django/django-sinyalleri-nasl-olusturulur-django-signals.md
      - django/djangoda-clickjack-tuzagnn-engeli-ve-kontrolu-xframeoptionsmiddleware.md
      - django/login-register-ve-logout-sayfalarinin-yapimi.md
  - OpenCV:
      - opencv/README.md
      - opencv/opencv-nedir-ve-kurulumu.md
      - opencv/opencv-resim-islemleri.md
      - opencv/opencv-video-islemleri.md
      - opencv/opencvde-cizim-fonksiyonlar.md
      - opencv/boya-frcas-olarak-fare.md
      - opencv/renk-paleti-olarak-parca-cubugu-trackbar.md
      - opencv/goruntulerle-ilgili-temel-islemler.md
      - opencv/goruntulerde-aritmetik-islemler.md
      - opencv/performans-olcum-ve-gelistirme-teknikleri.md
      - opencv/renk-alanlarn-degistirme.md
      - opencv/resim-esikleme.md
      - opencv/goruntunun-geometrik-donusumleri.md
      - opencv/goruntuyu-yumusatma-smoothing-images.md
      - opencv/morfolojik-donusumler.md
      - opencv/goruntu-gecisleri.md
      - opencv/canny-kenar-alglama.md
      - opencv/goruntu-piramitleri.md
      - opencv/konturler-contours.md
      - opencv/histogramlar.md
  - CPython:
      - cpython/README.md
      - cpython/cla.md
      - cpython/pr-goendermek.md
  - Javascript:
      - javascript/README.md
      - javascript/insertAdjacentHTML.md
  - Security:
      - security/README.md
      - security/clickjacking/README.md
      - security/clickjacking/clickjack-tuzagsaldrs-nedir.md
      - security/clickjacking/clickjack-tuzagn-engellemenin-yolu.md
      - security/clickjacking/clickjack-tuzagnn-engellenmesi.md
  - Sass:
      - sass/README.md
      - sass/sass-ve-scss-nedir-syntactically-awesome-stylesheets.md
      - sass/sass-kurulumu-linux-windows-ve-mac.md
      - sass/sass-scss-dersleri-sass-watch-degiskenler-nesting-import-mixin-include-ve-operatorler.md
      - sass/kosullu-durumlar-ve-donguler-if-else-if-else-for-while-each.md
      - sass/baz-sk-kullandgm-sassscss-mixinsleri.md
  - Cloud:
      - cloud/README.md
      - cloud/cloud-computing.md
      - cloud/serverless-nedir.md
      - cloud/aws-de-serverless-ve-lambda.md
      - cloud/aws-lambda-uzerine-serverless-uygulama-deployu-nasil-yapilir-.md
      - cloud/custom-image-kullanarak-aws-lambda-uzerine-sam-ile-deploy.md
      - cloud/aws-lambda-uzerine-fastapi-uygulamasini-sam-ile-nasil-deploy-edebilirim.md
  - Learn English:
      - learn-english/README.md
      - learn-english/prompts-for-learning-english-with-chatgpt.md
      - learn-english/tenses-in-english-an-overview.md
      - learn-english/models-an-overview.md
